#ifndef GUARD_CONFIG_BATTLE_FRONTIER_H
#define GUARD_CONFIG_BATTLE_FRONTIER_H

#define BATTLE_TYPE_BATTLE_TOWER_NEW (1 << 20)
#define BATTLE_TYPE_BATTLE_FACTORY (1 << 21)
#define BATTLE_TYPE_BATTLE_ARENA (1 << 22)
#define BATTLE_TYPE_BATTLE_DOME (1 << 23)
#define BATTLE_TYPE_BATTLE_PIKE (1 << 24)
#define BATTLE_TYPE_BATTLE_PALACE (1 << 25)
#define BATTLE_TYPE_BATTLE_PYRAMID (1 << 26)
#define BATTLE_TYPE_BATTLE_CASTLE (1 << 27)
#define BATTLE_TYPE_LC (1 << 28)
#define BATTLE_TYPE_ZU (1 << 29)
#define BATTLE_TYPE_PU (1 << 30)
#define BATTLE_TYPE_NU (1 << 31)
#define BATTLE_TYPE_RU (1 << 32)
#define BATTLE_TYPE_UU (1 << 33)
#define BATTLE_TYPE_UUBL (1 << 34)
#define BATTLE_TYPE_OU (1 << 35)
#define BATTLE_TYPE_DOUBLES (1 << 36)
#define BATTLE_TYPE_UBERS (1 << 37)
#define BATTLE_TYPE_1v1 (1 << 38)
#define BATTLE_TYPE_DRAFT_LEAGUE (1 << 39)
#define BATTLE_TYPE_RANDOM_BATTLES (1 << 40)
#define BATTLE_TYPE_OTHER_METAGAMES_PET_MODS (1 << 41)

#define BATTLE_FRONTIER_TIER_LEVEL_10 0
#define BATTLE_FRONTIER_TIER_LEVEL_20 1
#define BATTLE_FRONTIER_TIER_LEVEL_30 2
#define BATTLE_FRONTIER_TIER_LEVEL_40 3
#define BATTLE_FRONTIER_TIER_LEVEL_50 4
#define BATTLE_FRONTIER_TIER_LEVEL_OPEN_LEVEL 5
#define BATTLE_FRONTIER_TIER_LEVEL_100 6

#define BATTLE_FRONTIER_MATCH_OPTION_NORMAL 0
#define BATTLE_FRONTIER_MATCH_OPTION_RENTAL 1
#define BATTLE_FRONTIER_MATCH_OPTION_RANDOM_BATTLE 2
#define BATTLE_FRONTIER_MATCH_OPTION_SAMPLE_TEAM_RANDOM_BATTLE 3

#define BATTLE_FRONTIER_DIFFICULTY_EASY 0
#define BATTLE_FRONTIER_DIFFICULTY_NORMAL 1
#define BATTLE_FRONTIER_DIFFICULTY_HARD 2
#define BATTLE_FRONTIER_DIFFICULTY_IMPOSSIBLE 3

#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_GODLY_GIFT 0
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_CAMOMONS 1
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_CATEGORY_SWAP 2
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_CROSS_EVOLUTION 3
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_FRANTIC_FUSIONS 4
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_INHERITANCE 5
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_INVERSE 6
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_NATURE_SWAP 7
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_SKETCHMONS 8
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_THE_CARD_GAME 9
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_TIER_SHIFT 10
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_TRADEBACKS 11

#define BATTLE_FRONTIER_PARTY_LENGTH_SINGLES_STANDARD 3
#define BATTLE_FRONTIER_PARTY_LENGTH_SINGLES_MAX 6
#define BATTLE_FRONTIER_PARTY_LENGTH_DOUBLES_STANDARD 4
#define BATTLE_FRONTIER_PARTY_LENGTH_DOUBLES_MAX 6

#define BATTLE_FRONTIER_TIMER_NONE 0
#define BATTLE_FRONTIER_TIMER_STANDARD 300
#define BATTLE_FRONTIER_TIMER_FAST 30
#define BATTLE_FRONTIER_TIMER_BLITZ 10

#define BATTLE_FRONTIER_TRAINER_STRUCT_DEFAULT 0
#define BATTLE_FRONTIER_TRAINER_STRUCT_CUSTOM_MOVES 1
#define BATTLE_FRONTIER_TRAINER_STRUCT_CUSTOM_ITEMS 2
#define BATTLE_FRONTIER_TRAINER_STRUCT_CUSTOM 3

#endif // GUARD_CONFIG_BATTLE_FRONTIER_H