#ifndef GUARD_CONFIG_BATTLE_FRONTIER_H
#define GUARD_CONFIG_BATTLE_FRONTIER_H

#define BATTLE_FRONTIER_TIER_LEVEL_10 0
#define BATTLE_FRONTIER_TIER_LEVEL_20 1
#define BATTLE_FRONTIER_TIER_LEVEL_30 2
#define BATTLE_FRONTIER_TIER_LEVEL_40 3
#define BATTLE_FRONTIER_TIER_LEVEL_50 4
#define BATTLE_FRONTIER_TIER_LEVEL_OPEN_LEVEL 5
#define BATTLE_FRONTIER_TIER_LEVEL_100 6

#define BATTLE_FRONTIER_MATCH_OPTION_NORMAL 0
#define BATTLE_FRONTIER_MATCH_OPTION_RENTAL 1
#define BATTLE_FRONTIER_MATCH_OPTION_RANDOM_BATTLE 2
#define BATTLE_FRONTIER_MATCH_OPTION_SAMPLE_TEAM_RANDOM_BATTLE 3

#define BATTLE_FRONTIER_DIFFICULTY_EASY 0
#define BATTLE_FRONTIER_DIFFICULTY_NORMAL 1
#define BATTLE_FRONTIER_DIFFICULTY_HARD 2
#define BATTLE_FRONTIER_DIFFICULTY_IMPOSSIBLE 3

#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_GODLY_GIFT 0
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_CAMOMONS 1
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_CATEGORY_SWAP 2
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_CROSS_EVOLUTION 3
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_FRANTIC_FUSIONS 4
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_INHERITANCE 5
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_INVERSE 6
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_NATURE_SWAP 7
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_SKETCHMONS 8
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_THE_CARD_GAME 9
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_TIER_SHIFT 10
#define BATTLE_FRONTIER_OTHER_METAGAME_PET_MOD_TRADEBACKS 11

#define BATTLE_FRONTIER_PARTY_LENGTH_SINGLES_STANDARD 3
#define BATTLE_FRONTIER_PARTY_LENGTH_SINGLES_MAX 6
#define BATTLE_FRONTIER_PARTY_LENGTH_DOUBLES_STANDARD 4
#define BATTLE_FRONTIER_PARTY_LENGTH_DOUBLES_MAX 6

#define BATTLE_FRONTIER_TIMER_NONE 0
#define BATTLE_FRONTIER_TIMER_STANDARD 300
#define BATTLE_FRONTIER_TIMER_FAST 30
#define BATTLE_FRONTIER_TIMER_BLITZ 10

#define BATTLE_FRONTIER_TRAINER_STRUCT_DEFAULT 0
#define BATTLE_FRONTIER_TRAINER_STRUCT_CUSTOM_MOVES 1
#define BATTLE_FRONTIER_TRAINER_STRUCT_CUSTOM_ITEMS 2
#define BATTLE_FRONTIER_TRAINER_STRUCT_CUSTOM 3

#define BATTLE_TOWER_TRAINER_BATTLE 3

#define NUM_BATTLE_TOWER_TRAINERS 2
#define NUM_BATTLE_TOWER_MONS 24

#define FRONTIER_MON_SUNKERN        0
#define FRONTIER_MON_AZURILL        1
#define FRONTIER_MON_CATERPIE       2
#define FRONTIER_MON_WEEDLE         3
#define FRONTIER_MON_WURMPLE        4
#define FRONTIER_MON_RALTS          5
#define FRONTIER_MON_MAGIKARP       6
#define FRONTIER_MON_FEEBAS         7
#define FRONTIER_MON_METAPOD        8
#define FRONTIER_MON_KAKUNA         9
#define FRONTIER_MON_PICHU          10
#define FRONTIER_MON_SILCOON        11
#define FRONTIER_MON_CASCOON        12
#define FRONTIER_MON_IGGLYBUFF      13
#define FRONTIER_MON_WOOPER         14
#define FRONTIER_MON_TYROGUE        15
#define FRONTIER_MON_SENTRET        16
#define FRONTIER_MON_CLEFFA         17
#define FRONTIER_MON_SEEDOT         18
#define FRONTIER_MON_LOTAD          19
#define FRONTIER_MON_POOCHYENA      20
#define FRONTIER_MON_SHEDINJA       21
#define FRONTIER_MON_MAKUHITA       22
#define FRONTIER_MON_WHISMUR        23

#endif // GUARD_CONFIG_BATTLE_FRONTIER_H